server:
  port: 8082
spring:
  servlet:
    multipart:
      location: temp
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gac?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  mail:
    host: smtp.qq.com
    port: 465
    username: 2081896628@qq.com
    password: ixicfgyeegcucfic
    default-encoding: UTF-8
    from: 2081896628@qq.com
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

